### ISSUE TITLE
启动插件的时候报错，请看一下

### ISSUE THREAD

**Issue by kvgary** [Yanyutin753/pictureChange#12]
[WARNING][2024-04-07 15:21:38][pictureChange_wx.py:93] - [SD] init failed.
[WARNING][2024-04-07 15:21:38][plugin_manager.py:150] - Failed to init PICTURECHANGE, diabled. Expecting ':' delimiter: line 4 column 23 (char 76)

**Comment by Yanyutin753** [comment]
这个你得去改下面那个文件

**Comment by kvgary** [comment]
还请指教一下   是改pictureChange_wx.py这个文件么？

**Comment by kvgary** [comment]
"use_pictureChange": true,
    "max_number": 3,
    "request_bot_name"@bot"群聊请求机器人的名称，和config.json环境变量一致（只限一个）",
    "file_url": "file=D:\stable-diffusion-webui\output",
    "is_use_fanyi":false,

这个是之前的配置文件

**Comment by Yanyutin753** [comment]
跟这个没关系，代码显示不是这个错误

**Comment by Yanyutin753** [comment]
"request_bot_name"@bot"群聊请求机器人 这个错了
少了：

**Comment by kvgary** [comment]
已改，但还是报错。
[WARNING][2024-04-07 21:42:27][pictureChange_wx.py:93] - [SD] init failed.
[WARNING][2024-04-07 21:42:27][plugin_manager.py:150] - Failed to init PICTURECHANGE, diabled. Expecting value: line 4 column 24 (char 77)

<img width="635" alt="image" src="https://github.com/Yanyutin753/pictureChange/assets/16883380/b674066a-37e3-4f7e-a4cd-b26147bf4f17">
{
    "use_pictureChange": true,
    "max_number": 3,
    "request_bot_name":@bot"群聊请求机器人的名称，和config.json环境变量一致（只限一个）",
    "file_url": "file=D:\stable-diffusion-webui\output",
