### ISSUE TITLE
SD生成完图像后，提示文件不存在，请看一下。我检查路径是对的。

### ISSUE THREAD

**Issue by kvgary** [Yanyutin753/pictureChange#13]
<img width="959" alt="image" src="https://github.com/Yanyutin753/pictureChange/assets/16883380/9939677e-548a-41e0-8cda-61bc9270def4">

**Comment by Yanyutin753** [comment]
你是最新版吧 请按照readme 加一行代码

**Comment by Yanyutin753** [comment]
那个我已经pr了 下个cow的版本才会自动加上 你先添加吧

**Comment by kvgary** [comment]
@Yanyutin753  大佬，readme里面没看到需要加哪段代码，还请指点一下。

**Comment by kvgary** [comment]
是加这个么？
![image](https://github.com/Yanyutin753/pictureChange/assets/16883380/06ba1989-369b-4bd2-a63e-38cf9cd01ccd)

**Comment by kvgary** [comment]
可以了，谢谢
