### ISSUE TITLE
pictureChange/pictureChange_wx.py运行报错

### ISSUE THREAD

**Issue by xrggen** [Yanyutin753/pictureChange#2]
日志内容：[WARNING][2023-10-13 15:40:37][plugin_manager.py:113] - Failed to import plugin pictureChange: expected ':' (pictureChange_wx.py, line 1298)
检查1298行，漏了个“:”

ps：引入了百度云的API，能否不采用SD来处理呢？目前SD相关配置为必填

**Comment by Yanyutin753** [comment]
百度云api的画图一般般，我就想着只用sd来画图，百度云来加强画质
