### ISSUE TITLE
为啥企业微信没报错也收不到图片呢

### ISSUE THREAD

**Issue by LINWEN607** [Yanyutin753/pictureChange#4]
[INFO][2024-01-21 00:54:50][sdwebui.py:52] - [SD] image_query=现实 帅哥 海边
[INFO][2024-01-21 00:54:50][sdwebui.py:84] - [SD] keyword not matched: 现实
[INFO][2024-01-21 00:54:50][sdwebui.py:84] - [SD] keyword not matched: 帅哥
[INFO][2024-01-21 00:54:50][sdwebui.py:84] - [SD] keyword not matched: 海边
[INFO][2024-01-21 00:54:52][sdwebui.py:97] - [SD] translate prompt from zh to en
[INFO][2024-01-21 00:54:52][bridge.py:45] - create bot baidu for translate
[INFO][2024-01-21 00:54:52][sdwebui.py:101] - [SD] translate failed: baidu translate appid or appkey not set
[INFO][2024-01-21 00:54:52][sdwebui.py:102] - [SD] translated prompt=现实, 帅哥, 海边
[INFO][2024-01-21 00:54:52][sdwebui.py:105] - [SD] cover options={'sd_model_checkpoint': '《唯》· 超高清写实重制典藏版 _ OnlyRealistic _v30 典藏版'}
[INFO][2024-01-21 00:54:53][sdwebui.py:107] - [SD] params={'sampler_name': 'DPM++ 2M Karras', 'steps': 20, 'width': 512, 'height': 512, 'cfg_scale': 7, 'prompt': 'masterpiece, best quality, 现实, 帅哥, 海边', 'negative_prompt': '(low quality, worst quality:1.4),(bad_prompt:0.8), (monochrome:1.1), (greyscale)', 'enable_hr': False, 'hr_scale': 2, 'hr_upscaler': 'Latent', 'hr_second_pass_steps': 15, 'denoising_strength': 0.7}
[INFO][2024-01-21 00:54:57][wework_channel.py:298] - [WX] sendImage, receiver=S:1688851129438314_1688858442488739

**Comment by LINWEN607** [comment]
微信就不会

**Comment by Yanyutin753** [comment]
SD换成种子模式
