### ISSUE TITLE
以下今天2个文件仓库更新，麻烦作者适配下1.5.8版本的这2个文件，谢谢

### ISSUE THREAD

**Issue by swumagic** [Yanyutin753/pictureChange#7]
![image](https://github.com/Yanyutin753/pictureChange/assets/128472639/56a977ae-c626-45a1-8b1b-05960a234a7b)

**Comment by swumagic** [comment]
> OK了          chat channel.py删除了，不用替换了吗

**Comment by swumagic** [comment]
[ERROR][2024-03-27 18:05:56][plugin_manager.py:182] - Plugin Godcmd not found, but found in plugins.json
[ERROR][2024-03-27 18:05:56][plugin_manager.py:182] - Plugin pictureChange not found, but found in plugins.json
直接2个插件都识别不了了

**Comment by swumagic** [comment]
配置的文件应该没错吧，我把原版的godcmd替换后，可以识别管理权限（说明上午你刚更新的GODCMD还是有问题），但[ERROR][2024-03-27 18:13:12][plugin_manager.py:182] - Plugin pictureChange not found, but found in plugins.json，还是识别不了插件。
"use_pictureChange": true,
    "max_number": 3,
    "request_bot_name": "AI助手",
    "file_url": "file=M:/SD/sdwebui/outputs/",
    "is_use_fanyi":true,
    "api_key": "N7HSPQQh",
    "secret_key": "WWy19",
    "use_group": [],
    "max_size": 1150,
    "start": {
        "host": "127.0.0.1",
        "port": 7860,
        "use_https": false
    },
    "defaults": {
        "params": {
            "sampler_name": "Euler a",
            "steps": 20,
            "width": 512,
            "height": 512,
            "cfg_scale": 7.5,
            "prompt": "masterpiece, best quality",
            "negative_prompt": "nsfw,ugly,Vague,bad_hands,extra_hands,missing_fingers,broken hand,more than two hands,more than two legs,extra limbs,extra legs,unclear eyes,signature,watermark,username,blurry,worst_quality,low_quality,normal_quality",
            "enable_hr": false,
            "hr_scale": 2,
            "hr_upscaler": "4x-UltraSharp",
            "hr_second_pass_steps": 20,
            "denoising_strength": 0.35
        },
        "options": {
            "sd_model_checkpoint": "majicmixRealistic_v6"

**Comment by Yanyutin753** [comment]
明天再说吧 直接用服务器改的 没电脑

**Comment by Yanyutin753** [comment]
没错的 我的问题

**Comment by Yanyutin753** [comment]
你看看现在可以没

**Comment by swumagic** [comment]
我重新看下，谢谢大佬

**Comment by swumagic** [comment]
> 你看看现在可以没

重新启动了，Godcmd可以识别了，但插件pictureChange还是识别不了。
[ERROR][2024-03-28 01:01:36][plugin_manager.py:182] - Plugin pictureChange not found, but found in plugins.json
[DEBUG][2024-03-28 01:01:36][plugin.py:27] - loading plugin config, plugin_name=Godcmd, conf={'password': '7721107', 'admin_users': []}
[INFO][2024-03-28 01:01:36][godcmd.py:226] - [Godcmd] inited

**Comment by swumagic** [comment]
插件pictureChange还是一直识别不了，[ERROR][2024-03-28 01:01:36][plugin_manager.py:182] - Plugin pictureChange not found, but found in plugins.json

**Comment by swumagic** [comment]
输入#enImageChange指令就出错
Context(type=TEXT, content=#enImageChange, kwargs={})
[DEBUG][2024-03-28 04:31:22][plugin_manager.py:189] - Plugin SUMMARY triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-03-28 04:31:22][main.py:90] - [Summary] insert record:  2392096391770  #enImageChange TEXT 171157 1
[DEBUG][2024-03-28 04:31:22][chat_channel.py:354] - [WX] consume context: Context(type=TEXT, content=#enImageChange, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x000002EAB1F7B820>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@73ce8fb14e6353b472
c03f7', 'receiver': '@73ce8fb14e6320be2dc630c03f7'})
[DEBUG][2024-03-28 04:31:22][chat_channel.py:179] - [WX] ready to handle context: Context(type=TEXT, content=#enImageChange, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x0000021F7B820>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@73ce8fb14e6353b40c03f7', 'receiver': '@73ce8fb14e6353b47c03f7'})
[DEBUG][2024-03-28 04:31:22][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-28 04:31:22][godcmd.py:236] - [Godcmd] on_handle_context. content: #enImageChange
[ERROR][2024-03-28 04:31:22][chat_channel.py:312] - Worker return exception: name 'curdir' is not defined
Traceback (most recent call last):
  File "M:\SD\Python31011\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "M:\SD\git\chatgpt-on-wechat\channel\chat_channel.py", line 181, in _handle
    reply = self._generate_reply(context)
  File "M:\SD\git\chatgpt-on-wechat\channel\chat_channel.py", line 191, in _generate_reply
    e_context = PluginManager().emit_event(
  File "M:\SD\git\chatgpt-on-wechat\plugins\plugin_manager.py", line 191, in emit_event
    instance.handlers[e_context.event](e_context, *args, **kwargs)
  File "M:\SD\git\chatgpt-on-wechat\plugins\godcmd\godcmd.py", line 403, in on_handle_context
    config_path = os.path.join(curdir, "../../config.json")
NameError: name 'curdir' is not defined
