### ISSUE TITLE
发送图片后不进行操作有没有过期时间？

### ISSUE THREAD

**Issue by Cxleos** [Yanyutin753/pictureChange#9]
遇到一个问题，"max_number": 3, 三个人发送图片，但没进行操作，后面再发送图片就一直提示排队了，前面的不操作后面的一直排队。

**Comment by Yanyutin753** [comment]
哈哈哈哈哈哈哈 这个bug被发现了

**Comment by Yanyutin753** [comment]
这个暂时解决不了

**Comment by Yanyutin753** [comment]
得在函数加个定时删除

**Comment by Yanyutin753** [comment]
不太会在插件里面写定时

**Comment by Cxleos** [comment]
那，"max_number": 3设置成0 能不能关闭这个功能？

**Comment by Yanyutin753** [comment]
0还不行 可以把值调大点

**Comment by Yanyutin753** [comment]
或者我改个逻辑 直接发图片 显示文案之后 就减掉这个值

**Comment by Yanyutin753** [comment]
这样可以有效降低并发

**Comment by Cxleos** [comment]
能不能改个判断啊，开始生成图片再进入队列？没生成图片命令之前那些都不进入队列，然后tmp文件夹定时清理一下，避免图片把硬盘占满了

**Comment by Yanyutin753** [comment]
你来改改 pr一下也行 我现在改代码的时间不多

**Comment by Yanyutin753** [comment]
定时清除这个简单 我都是写一个脚本删的

**Comment by swumagic** [comment]
> 定时清除这个简单 我都是写一个脚本删的
大佬更新后，直接2个插件都无法识别了，麻烦更新下，谢谢
[ERROR][2024-03-27 18:05:56][plugin_manager.py:182] - Plugin Godcmd not found, but found in plugins.json
[ERROR][2024-03-27 18:05:56][plugin_manager.py:182] - Plugin pictureChange not found, but found in plugins.json
直接2个插件都识别不了了

**Comment by Yanyutin753** [comment]
试试最新版的 我用手机改的

**Comment by swumagic** [comment]
之前就更新试了，pictureChange和 Godcmd还是一样 不能识别。

**Comment by Yanyutin753** [comment]
重新enablep一下

**Comment by Cxleos** [comment]
看看是不是缺依赖，
pictureChange目录执行 
pip3 install -r requirements.txt
pip3 install oauthlib

然后插件对话扫描一下#scanp

**Comment by swumagic** [comment]
oauthlib之前这个依赖没有安装，其他依赖都安装了，不过安装了这个oauthlib也没有用，还是识别不了插件
[ERROR][2024-03-28 03:58:34][plugin_manager.py:182] - Plugin pictureChange not found, but found in plugins.json

**Comment by swumagic** [comment]
> 看看是不是缺依赖， pictureChange目录执行 pip3 install -r requirements.txt pip3 install oauthlib
> 
> 然后插件对话扫描一下#scanp

谢谢，可以识别插件了，但现在 SD 后台生产创作图片后（我在SD的保存图片文件里看到有图生图的照片在），但都没发到微信上，好像就被插件自己删除还是其他问题，后面放大指令也看不到照片，说放大失败。



流程DEBUG如下

[INFO][2024-03-28 05:49:33][pictureChange_wx.py:1500] - 图片读取成功
[INFO][2024-03-28 05:49:33][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=🚀图片生成中～～～
⏳请您耐心等待1-2分钟
✨请稍等片刻✨✨
❤️感谢您的耐心与支持), receiver=@d0709981964dc97e072e4e928
使用了其他模型
[INFO][2024-03-28 05:50:34][wechat_channel.py:237] - [WX] sendImage, receiver=@d0709981964dc97e072eae928
[INFO][2024-03-28 05:50:34][pictureChange_wx.py:1585] - 文件已成功删除
[DEBUG][2024-03-28 05:50:34][plugin_manager.py:194] - Plugin PICTURECHANGE breaked event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-28 05:50:34][chat_channel.py:183] - [WX] ready to decorate reply: Reply(type=TEXT, content=🔥 图片创作成功!

[DEBUG][2024-03-28 05:53:33][plugin_manager.py:194] - Plugin PICTURECHANGE breaked event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-28 05:53:33][chat_channel.py:183] - [WX] ready to decorate reply: Reply(type=TEXT, content=[😭放大图片失败]
快联系管理员解决问题吧🥰🥰🥰)
[DEBUG][2024-03-28 05:53:33][chat_channel.py:293] - [WX] ready to send reply: Reply(type=TEXT, content=[黑科]
[😭放大图片失败]
快联系管理员解决问题吧🥰🥰🥰


![image](https://github.com/Yanyutin753/pictureChange/assets/128472639/a9795eb5-9c79-4c1e-af2a-917a5a215a3d)

![image](https://github.com/Yanyutin753/pictureChange/assets/128472639/9175c74e-184e-4d51-afa9-df560ed464e7)

**Comment by Yanyutin753** [comment]
放大失败是因为你没有填好参数，或者没有使得图像以种子的形式保存，可以看看readme，而四张图未显示，是因为最新版本对于发送二进制图片文件有BUG，我已经pull request了，现在最简单的办法就是更改一下文件

**Comment by Yanyutin753** [comment]
![image](https://github.com/Yanyutin753/pictureChange/assets/132346501/3160efd2-f1da-4c27-a34b-321d470c417b)
## 加一行代码即可

**Comment by Yanyutin753** [comment]
@Cxleos  你试试最新的代码，改了一下逻辑，只有用到sd才会计数，画完自动忽略计数，因为没有测试环境，我粗略的改了大致代码，你测试一下

**Comment by swumagic** [comment]
> @Cxleos  你试试最新的代码，改了一下逻辑，只有用到sd才会计数，画完自动忽略计数，因为没有测试环境，我粗略的改了大致代码，你测试一下

大佬，那个 chat-channl.py直接用原版，不用替换你之前的了吗？
另外百度云可以替换replicate api来画图么？replicate画图成本便宜且可以随便设置选择模型。

**Comment by swumagic** [comment]
> 放大失败是因为你没有填好参数，或者没有使得图像以种子的形式保存，可以看看readme，而四张图未显示，是因为最新版本对于发送二进制图片文件有BUG，我已经pull request了，现在最简单的办法就是更改一下文件

我图像是种子形式，放大参数我按照你的参考填好了，就是放大是本地sd放大，还是调用的百度云api放大，百度云貌似要后台先付款才可以用。

**Comment by Yanyutin753** [comment]
要改那个我发的图片那个文件

**Comment by Yanyutin753** [comment]
我不用百度云的 百度云可以不用填都行 百度云只是用来图像清晰而已

**Comment by swumagic** [comment]
> 要改那个我发的图片那个文件

 chat-channl.py不用替换你之前的了吗？我看之前你有，昨天你删除了。
大佬，可以replicate 插件把合并下，方便railway使用。replicate画图成本便宜且也可以随便设置选择任何模型。

**Comment by swumagic** [comment]
> 放大失败是因为你没有填好参数，或者没有使得图像以种子的形式保存，可以看看readme，而四张图未显示，是因为最新版本对于发送二进制图片文件有BUG，我已经pull request了，现在最简单的办法就是更改一下文件


作者大大，目前SD第一次的4合一图片可以微信发出来，但放大和变换命令还是不行（我按照作者你的原设置参数数值没变），结果一直显示失败，应该哪里还有BUG。

放大指令错误的debug如下。


[DEBUG][2024-03-29 01:56:07][chat_channel.py:300] - Worker return success, session_id = @adeb410b4422eb8a8813
[DEBUG][2024-03-29 01:56:16][wechat_channel.py:180] - [WX]receive text msg: {"MsgId": "37669636012", "FromUserName": "@adeb41025b8a8813", "ToUserName": "@5aeb4a90e4912759ff5c1676", "MsgType": 1, "Content": "🤖 放大 img2img-images/4079420173.png 3", "Status": 3, "ImgStatus": 1, "CreateTime": 1711648576, "VoiceLength": 0, "PlayLength": 0, "FileName": "", "FileSize": "", "MediaId": "", "Url": "", "AppMsgType": 0, "StatusNotifyCode": 0, "StatusNotifyUserName": "", "RecommendInfo": {"UserName": "", "NickName": "", "QQNum": 0, "Province": "", "City": "", "Content": "", "Signature": "", "Alias": "", "Scene": 0, "VerifyFlag": 0, "AttrStatus": 0, "Sex": 0, "Ticket": "", "OpCode": 0}, "ForwardFlag": 0, "AppInfo": {"AppID": "", "Type": 0}, "HasProductId": 0, "Ticket": "", "ImgHeight": 0, "ImgWidth": 0, "SubMsgType": 0, "NewMsgId": 37662636012, "OriContent": "", "EncryFileName": "", "User": {"MemberList": [], "Uin": 0, "UserName": "@adeb410b4b8a8813", "NickName": "余", "HeadImgUrl": "/cgi-bin/mmwebwx-bin/webwxgeticon?seq=734925&username=@adeb410ba8813&skey=@crypt_e9623dcd_62da143388", "ContactFlag": 3, "MemberCount": 0, "RemarkName": "", "HideInputBarFlag": 0, "Sex": 1, "Signature": "天道 酬勤——业精于勤荒于嬉，行成于思毁于随！", "VerifyFlag": 0, "OwnerUin": 0, "PYInitial": "Y", "PYQuanPin": "yu", "RemarkPYInitial": "", "RemarkPYQuanPin": "", "StarFriend": 0, "AppAccountFlag": 0, "Statues": 0, "AttrStatus": 16879719, "Province": "广东", "City": "广州", "Alias": "", "SnsFlag": 177, "UniFriend": 0, "DisplayName": "", "ChatRoomId": 0, "KeyWord": "y", "EncryChatRoomId": "", "IsOwner": 0}, "Type": "Text", "Text": "🤖 放大 img2img-images/4079420173.png 3"}, cmsg=ChatMessage: id=376626012, create_time=17118576, ctype=TEXT, content=🤖 放大 img2img-images/4079420173.png 3, from_user_id=@adeb410b4422e8225b8a8813, from_user_nickname=余, to_user_id=@5aeb4a90e491f1347e085f8722759ff5c1676, to_user_nickname=永川地产安娜, other_user_id=@adeb410b44228225b8a8813, other_user_nickname=余, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, at_list=None
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin SUMMARY triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-03-29 01:56:16][main.py:90] - [Summary] insert record: 余 37662569636012 余 🤖 放 大 img2img-images/4079420173.png 3 TEXT 1711648576 1
[DEBUG][2024-03-29 01:56:16][chat_channel.py:345] - [WX] consume context: Context(type=TEXT, content= 🤖 放大 img2img-images/4079420173.png 3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x0000028B2C5436D0>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@adeb410b448813', 'receiver': '@adeb410b813'})
[DEBUG][2024-03-29 01:56:16][chat_channel.py:168] - [WX] ready to handle context: Context(type=TEXT, content=🤖 放大 img2img-images/4079420173.png 3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x0000028436D0>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@adeb410ba68225b8a8813', 'receiver': '@adeb410b448a8813'})
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 01:56:16][godcmd.py:236] - [Godcmd] on_handle_context. content: 🤖 放大 img2img-images/4079420173.png 3
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin BLACKROOM triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 01:56:16][keyword.py:52] - [keyword] on_handle_context. content: 🤖 放大 img2img-images/4079420173.png 3
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin BANWORDS triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 01:56:16][banwords.py:65] - [Banwords] on_handle_context. content: 🤖 放大 img2img-images/4079420173.png 3
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:189] - Plugin PICTURECHANGE triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 01:56:16][plugin_manager.py:194] - Plugin PICTURECHANGE breaked event Event.ON_HANDLE_CONTEXT

[DEBUG][2024-03-29 01:56:16][chat_channel.py:172] - [WX] ready to decorate reply: Reply(type=TEXT, content=[😭放大图片失败]
快联系管理员解决问题吧🥰🥰🥰)
[DEBUG][2024-03-29 01:56:16][chat_channel.py:284] - [WX] ready to send reply: Reply(type=TEXT, content=[黑]
[😭放大图片失败]
快联系管理员解决问题吧🥰🥰🥰
[更多]), context: Context(type=TEXT, content=🤖 放大 img2img-images/4079420173.png 3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x000002C5436D0>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@adeb410b4428a8813', 'receiver': '@adeb410b4428a8813'})
[INFO][2024-03-29 01:56:16][wechat_channel.py:214] - [WX] sendMsg=Reply(type=TEXT, content=[黑]
[😭放大图片失败]
快联系管理员解决问题吧🥰🥰🥰




变换指令错误的debug如下

[DEBUG][2024-03-29 02:05:03][wechat_channel.py:180] - [WX]receive text msg: {"MsgId": "779287862", "FromUserName": "@adeb4105a68225b8a8813", "ToUserName": "@5aeb4a90e491f13ad7a2f2759ff5c1676", "MsgType": 1, "Content": "🎡 变换 img2img-images/4079420173.png  3", "Status": 3, "ImgStatus": 1, "CreateTime": 17119104, "VoiceLength": 0, "PlayLength": 0, "FileName": "", "FileSize": "", "MediaId": "", "Url": "", "AppMsgType": 0, "StatusNotifyCode": 0, "StatusNotifyUserName": "", "RecommendInfo": {"UserName": "", "NickName": "", "QQNum": 0, "Province": "", "City": "", "Content": "", "Signature": "", "Alias": "", "Scene": 0, "VerifyFlag": 0, "AttrStatus": 0, "Sex": 0, "Ticket": "", "OpCode": 0}, "ForwardFlag": 0, "AppInfo": {"AppID": "", "Type": 0}, "HasProductId": 0, "Ticket": "", "ImgHeight": 0, "ImgWidth": 0, "SubMsgType": 0, "NewMsgId": 7792300987862, "OriContent": "", "EncryFileName": "", "User": {"MemberList": [], "Uin": 0, "UserName": "@adeb410b445b8a8813", "NickName": "余", "HeadImgUrl": "/cgi-bin/mmwebwx-bin/webwxgeticon?seq=734025&username=@adeb410b44228813&skey=@crypt_e9623dcd_6ca417e6572da143388", "ContactFlag": 3, "MemberCount": 0, "RemarkName": "", "HideInputBarFlag": 0, "Sex": 1, "Signature": "天道酬勤——业精于勤荒于嬉，行成于思毁于随！", "VerifyFlag": 0, "OwnerUin": 0, "PYInitial": "YH", "PYQuanPin": "yu", "RemarkPYInitial": "", "RemarkPYQuanPin": "", "StarFriend": 0, "AppAccountFlag": 0, "Statues": 0, "AttrStatus": 16819, "Province": "广东", "City": "广州", "Alias": "", "SnsFlag": 177, "UniFriend": 0, "DisplayName": "", "ChatRoomId": 0, "KeyWord": "yuh", "EncryChatRoomId": "", "IsOwner": 0}, "Type": "Text", "Text": "🎡 变换 img2img-images/4079420173.png  3"}, cmsg=ChatMessage: id=779230987862, create_time=1711104, ctype=TEXT, content=🎡 变换 img2img-images/4079420173.png  3, from_user_id=@adeb410b445b8a8813, from_user_nickname=余, to_user_id=@5aeb4a90e491f13497a2f2759ff5c1676, to_user_nickname=永川地产安娜, other_user_id=@adeb4125b8a8813, other_user_nickname=余, is_group=False, is_at=False, actual_user_id=None, actual_user_nickname=None, at_list=None
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin SUMMARY triggered by event Event.ON_RECEIVE_MESSAGE
[DEBUG][2024-03-29 02:05:03][main.py:90] - [Summary] insert record: 余 779230016987862 余 🎡  变换 img2img-images/4079420173.png  3 TEXT 1711649104 1
[DEBUG][2024-03-29 02:05:03][chat_channel.py:345] - [WX] consume context: Context(type=TEXT, content= 🎡 变换 img2img-images/4079420173.png  3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x000002841C00>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@adeb410b4422eb940c5a8813', 'receiver': '@adeb410b4422eb98a8813'})
[DEBUG][2024-03-29 02:05:03][chat_channel.py:168] - [WX] ready to handle context: Context(type=TEXT, content=🎡 变换 img2img-images/4079420173.png  3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x0000C541C00>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@adeb410b4422eb225b8a8813', 'receiver': '@adeb410b44c5a68225b8a8813'})
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin GODCMD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 02:05:03][godcmd.py:236] - [Godcmd] on_handle_context. content: 🎡 变换 img2img-images/4079420173.png  3
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin BLACKROOM triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin KEYWORD triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 02:05:03][keyword.py:52] - [keyword] on_handle_context. content: 🎡 变换 img2img-images/4079420173.png  3
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin TIMETASK triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin BANWORDS triggered by event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 02:05:03][banwords.py:65] - [Banwords] on_handle_context. content: 🎡 变换 img2img-images/4079420173.png  3
[DEBUG][2024-03-29 02:05:03][plugin_manager.py:189] - Plugin PICTURECHANGE triggered by event Event.ON_HANDLE_CONTEXT
[ERROR][2024-03-29 02:05:03][pictureChange_wx.py:1520] - [SD画图失败] exception: 3
[INFO][2024-03-29 02:05:04][wechat_channel.py:217] - [WX] sendMsg=Reply(type=ERROR, content=[😭SD画图 失败] 3
快联系管理员解决问题吧🥰🥰🥰), receiver=@adeb410b4422e8225b8a8813
[DEBUG][2024-03-29 02:05:04][plugin_manager.py:194] - Plugin PICTURECHANGE breaked event Event.ON_HANDLE_CONTEXT
[DEBUG][2024-03-29 02:05:04][chat_channel.py:172] - [WX] ready to decorate reply: Reply(type=INFO, content=string)
[DEBUG][2024-03-29 02:05:04][chat_channel.py:284] - [WX] ready to send reply: Reply(type=INFO, content=[INFO]
string), context: Context(type=TEXT, content=🎡 变换 img2img-images/4079420173.png  3, kwargs={'isgroup': False, 'msg': <channel.wechat.wechat_message.WechatMessage object at 0x0028B41C00>, 'origin_ctype': <ContextType.TEXT: 1>, 'openai_api_key': None, 'gpt_model': None, 'session_id': '@adeb410b0c5a68225b8a8813', 'receiver': '@adeb414228a8813'})
[INFO][2024-03-29 02:05:04][wechat_channel.py:217] - [WX] sendMsg=Reply(type=INFO, content=[INFO]
string), receiver=@adeb410b4422e225b8a8813
[DEBUG][2024-03-29 02:05:04][chat_channel.py:300] - Worker return success, session_id = @adeb410b8a8813

**Comment by Yanyutin753** [comment]
路径填对了吗 路径是你图片生成的位置

**Comment by Yanyutin753** [comment]
"file_url": "file=F:/sd-webui-aki_v4.7/outputs/,  #这个地址是你图片生成的地址"

**Comment by swumagic** [comment]
> "file_url": "file=F:/sd-webui-aki_v4.7/outputs/,  #这个地址是你图片生成的地址"

嗯。这里我之前就改了，写的格式和你一样，"file_url": "file=M:/sdwebui/outputs/,不过这个目录路径是所有SD图片生成的子目录总文件夹。
问下这里文件路径是到 生成图生图的4合一图片的目录还是图生图的单图目录。

**Comment by Yanyutin753** [comment]
就总目录就行output

**Comment by swumagic** [comment]
> 就总目录就行output
我之前就是这样设置的，那不能放大和变换的问题就是其他bug原因造成的。看下大佬能否修复下。我上面有debug

**Comment by swumagic** [comment]
> 就总目录就行output

![image](https://github.com/Yanyutin753/pictureChange/assets/128472639/603fb43d-be08-423b-938b-7e158b06a03c)

**Comment by Yanyutin753** [comment]
加我吧 这上面不好看

**Comment by Yanyutin753** [comment]
微信

**Comment by swumagic** [comment]
> 加我吧 这上面不好看 

大佬微信号发下，直接捐助过，但没微信号，谢谢

**Comment by Yanyutin753** [comment]
你看看我别的项目就有了

**Comment by swumagic** [comment]
大佬，Clivia这个微信是你本人哈，想不到之前加过。
